In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

#import required libraries for modelling and model evaluation
from sklearn.linear_model import Ridge, Lasso, LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [8]:
data = pd.read_csv('energydata_complete.csv')
data.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [9]:
data.drop(columns=['date', 'lights'],inplace=True)
data.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,60,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,50,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,50,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,45.723333,17.166667,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,60,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,45.530000,17.200000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [10]:
scalar = MinMaxScaler()
normal_df = pd.DataFrame(scalar.fit_transform(data),columns=data.columns)
normal_df.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.046729,0.32735,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.046729,0.32735,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.037383,0.32735,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,...,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.037383,0.32735,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.046729,0.32735,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,...,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611

In [11]:
X = normal_df.drop(['Appliances'], axis=1)

#target
y = normal_df['Appliances']

In [12]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Quiz Questions
## Question 1: In the Linear regression, L2 regularization is equivalent to imposing a: Answer: Gaussian prior.

## Question 2: Cross validation: Answer: Is quaranteed to prevent overfitting.

## Question 3: Ridge Regression: Answer: Reduces variance at the expence of higher bias.

## Question 4: In the different terms of the bias-tradeoff, which of the following is substantially more harmful to the test error than the training error? Answer: Variance.

## Question 5: What can you use to find the best fit line for Linear Regression? Answer: Least Square Error.

## Question 6: Which of the following is true about outliers in linear regression? Answer: Linear regression is sensitive to outliers. 

## Question 7: How many coefficients do you need to estimate a simple linear regression model(One, independent variable)? Answer: 2. 

## Question 8: Adding more bias functions in a linear model: Answer: Decreases model bias.

## Question 9: A best fit line relating X and Y has a R-squared value of 0.75. How do I interpret this information? Answer: 75% of the variance in Y is explained by X.

## Question 10: The Lasso can be interpreted as least-squares regression where: Answer: Weights are regularized with the L1 norm.

## Question 11: Which of these assumptions of Linear Regression? Answer: Multivariate normality

## Question 12: From the dataset, fit a linear model on the relationship between the temperature in the living room in Celsius (x = T2) and the temperature outside the building (y = T6). What is the R^2 value in two D.P? Answer: 0.64

In [15]:
train_X = x_train[['T2']]
train_y = x_train[['T6']]
test_X = x_test[['T2']]
test_y = x_test[['T6']]

model = LinearRegression()

model.fit(train_X,train_y)
y_pred = model.predict(test_X)
print(r2_score(test_y,y_pred))

0.6427789637197381

## Question 13: What is the mean absolute error

In [17]:
lin_reg = LinearRegression()
lin_reg.fit(x_train,y_train)
y_pred_new = lin_reg.predict(x_test)
mean_absolute_error(y_test,y_pred_new)

0.05013264567958296

## Question 14: What is the Residual Sum of Squares(in two decimal places)

In [23]:
round(np.sum(np.square(y_test - y_pred_new)), 2)

45.34

## Question 15: What is the Root Mean Suared Error(in three decimal places)

In [22]:
round(np.sqrt(mean_squared_error(y_test,y_pred_new)),3)

0.088

## Question 16: What is the Coefficient of Determination(in two decimal places)

In [26]:
round(r2_score(y_test,y_pred_new),2)

0.15

## Question 17: Obtain the feature weights from your linear model above. Which features have the lowest and highest weights respectively?

In [31]:
feature_wts = model.coef_

## Question 17: Obtain the feature weights from your linear model above. Which features have the lowest and highest weights respectively?

In [33]:

def get_weights_df(model, feat, col_name):
  #this function returns the weight of every feature
  weights = pd.Series(model.coef_, feat.columns).sort_values()
  weights_df = pd.DataFrame(weights).reset_index()
  weights_df.columns = ['Features', col_name]
  weights_df[col_name].round(3)
  return weights_df

# Execute the get_weight function and store in dataframe
linear_weights_df = get_weights_df(lin_reg, x_train, 'Linear_weight')

linear_weights_df

       Features  Linear_weight
0           rv2  -1.966888e+11
1          RH_2  -4.570041e-01
2         T_out  -3.217851e-01
3            T2  -2.364318e-01
4            T9  -1.900450e-01
5          RH_8  -1.576727e-01
6        RH_out  -7.754609e-02
7          RH_7  -4.453700e-02
8          RH_9  -3.980948e-02
9            T5  -1.558382e-02
10           T1  -3.281051e-03
11  Press_mm_hg   6.879429e-03
12           T7   1.039964e-02
13   Visibility   1.230387e-02
14         RH_5   1.603128e-02
15         RH_4   2.638271e-02
16           T4   2.897272e-02
17    Windspeed   2.922762e-02
18         RH_6   3.806349e-02
19         RH_3   9.609141e-02
20           T8   1.020407e-01
21    Tdewpoint   1.177307e-01
22           T6   2.364998e-01
23           T3   2.907382e-01
24         RH_1   5.536678e-01
25          rv1   1.966888e+11

## Question 18: Train a Ridge Regression model with an alpha value of 0.4. Is there any change to the root mean squared error(RMSE) when evaluated on the test set?

In [34]:
ridge = Ridge()

ridge.fit(x_train, y_train)

pred = ridge.predict(x_test)

ridge_rmse = round(np.sqrt(mean_squared_error(y_test, pred)), 3)

print(f'The RMSE score for the rigde model with default aplha value when evaluated on the test set is: {ridge_rmse}')

ridge_reg = Ridge(alpha=0.4)

ridge_reg.fit(x_train, y_train)


new_pred = ridge_reg.predict(x_test)

ridge_rmse_new = round(np.sqrt(mean_squared_error(y_test, new_pred)), 3)

print(f'The RMSE score for the rigde model with default aplha value when evaluated on the test set is: {ridge_rmse_new}')

print('There is no change in the RMSE scores')

The RMSE score for the rigde model with default aplha value when evaluated on the test set is: 0.088
The RMSE score for the rigde model with default aplha value when evaluated on the test set is: 0.088
There is no change in the RMSE scores

## Question 19: Train a Lasso regression model with an aplha value of 0.001 and obtain the new feature weights with it. How many of the features have non-zero feature weights?

In [35]:
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(x_train, y_train)
lasso_preds = lasso_reg.predict(x_test)

def get_weights_df(model, feat, col_name):

  weights = pd.Series(model.coef_, feat.columns).sort_values()
  weights_df = pd.DataFrame(weights).reset_index()
  weights_df.columns = ['Features', col_name]
  weights_df[col_name].round(3)
  return weights_df

lasso_weights_df = get_weights_df(lasso_reg, x_train, 'Lasso_weight')

non_zero_weights = lasso_weights_df[lasso_weights_df['Lasso_weight'] != 0]

print(non_zero_weights)
print(f'The total features with non-zero feature weights are equal to: {len(non_zero_weights)}')

     Features  Lasso_weight
0      RH_out     -0.049557
1        RH_8     -0.000110
24  Windspeed      0.002912
25       RH_1      0.017880
The total features with non-zero feature weights are equal to: 4

## Question 20: What is the new RMSE with Lasso Regression (in 3 decimal places)

In [36]:
round(np.sqrt(mean_squared_error(y_test, lasso_preds)), 3)

0.094